### ISSUE TITLE
Dependency mtdowling/cron-expression has php >= 7.0

### ISSUE THREAD

**Issue by teddywest32** [omnilight/yii2-scheduling#23]
This repository has the php version >=5.4 but the dependency library [mtdowling/cron-expression](https://github.com/mtdowling/cron-expression) has php version >=7.0

This repository might need to lock down the version of mtdowling/cron-expression to 1.0.4

Have a look in their repository for the proof:

https://github.com/mtdowling/cron-expression/blob/master/composer.json#L13

**Comment by gietos** [comment]
@teddywest32 dependency constraint is correct. Now it's `~1.0`, which is equivalent to `>=1.0 <2.0.0`. PHP 5.* support mentioned by you is unreleased and I believe will be merged into 2.*, if it will happen after all, because package is no longer maintained (see https://github.com/mtdowling/cron-expression/pull/165)
